name: CookiePvP
version: 3.0
author: Cangasso e MoradorDeRua
description: Plugin de KitPvP
main: me.cangasso.main.Main
commands:
  groupset:
  friends:
  tempgroupset:
  builder:
  hrc:
  admin:
  aplicar:
  hg:
  loja:
  store:
  kit:
  giveall:
  ip:
  semiyt:
  pro:
  removeall:
  score:
  fly:
  duvida:
  tag:
  tags:
  tp:
  gamemode:
  gm:
  spro:
  youtuber:
  chat:
  setholograma:
  sc:
  ban:
  tempban:
  kick:
  pardon:
  mute:
  ipban:
  tempmute:
  dica:
  report:
  set:
  spawn:
  warp:
  speed1v1:
  tell:
   aliases: [msg]
  reidamesa:
  rdm:
  join:
  entrar:
  sair:
  leave:
  specs:
  ban:
  tempban:
  kick:
  pardon:
  mute:
  ipban:
  tempmute:
  bancheck:
  mutecheck:
  bc:
  account:
  inv:
  invsee:
  getip:
  horas:
  rank:
  ranks:
  ping:
  acc:
  tpall:
  vis:
  invis:
  removerhead:
  removerhat:
  removehead:
  removehat:
  manutencao:
  cage:
  autosoup:
  tphere:
  s:
  stopserver:
  kickall:
  login:
  register:
  monitorar:
  skit:
  dano:
  pvp:
  clearall:
  tweetar:
  head:
  addpermission:
  removepermission:
  check:
  givevip:
  giveyoutuber:
  givebuilder:
  givekit: